const EMPLOYEE_ENTITY = "employee";
const CAFE_ENTITY = "cafe";
const EMPLOYEE_PHONE_NO_MIN_LENGTH = 8;
const VALID_STARTING_PHONE_NUMBERS = ["8", "9"];
const MINIMUM_NAME_LENGTH = 6;
const MAXIMUM_NAME_LENGTH = 10;
const MAXIMUM_DESCRIPTION_LENGTH = 256;
const VALID_GENDERS = ["Male", "Female"];
const ALL = "All";
const PUT = "PUT";
const POST = "POST";

export {
  EMPLOYEE_ENTITY,
  CAFE_ENTITY,
  EMPLOYEE_PHONE_NO_MIN_LENGTH,
  VALID_STARTING_PHONE_NUMBERS,
  MINIMUM_NAME_LENGTH,
  MAXIMUM_NAME_LENGTH,
  MAXIMUM_DESCRIPTION_LENGTH,
  VALID_GENDERS,
  ALL,
  PUT,
  POST
};
